apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace : n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n:latest
          ports:
            - containerPort: 5678
          env:
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: admin-user
            - name: N8N_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: admin-password
            - name: N8N_DATABASE_SQLITE_FILE
              value: "/data/n8n.sqlite"
          volumeMounts:
            - name: n8n-data
              mountPath: /data
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-pvc
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
  namespace : n8n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  namespace : n8n
spec:
  selector:
    app: n8n
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
  type: ClusterIP
